group-15-dd2480/Assignment-1

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/CircleContainmentCheckTest.java, src/test/java/org/dd2480/MainTest.java
Added a new function `circleContainmentCheck` to check if a set of points can be contained within or on a circle with a given radius.
- Added `circleContainmentCheck` function
- Added 5 unit tests for the `circleContainmentCheck` function
Closes #7
=> feat: Add circleContainmentCheck function

.github/workflows/maven.yml
Creates a CI pipeline using github actions.
Runs `mvn package` to test and build the project.
Closes #9
=> feat: create ci pipeline (#9)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic1Test.java
Added a function to evaluate the first launch interceptor condition.
- Added `lic1` function
- Added 6 unit tests for `lic1`
Closes #13
=> feat: Add LIC 1 evaluator function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/TriangeAreaTest.java
Added a function to calculate the area of a triangle.
* Added `triangleArea` function
* Added unit tests
Closes #6
=> feat: add function to calculate area of a triangle (#6)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic4Test.java, src/test/java/org/dd2480/QuadrantTest.java
Add a function to evaluate the fourth launch interceptor condition.
* Add `lic4` function
* Add 4 unit tests for `lic4`
* Add `quadrant` utility function for `lic4`
* Add 4 unit tests for `quadrant`
Closes #1
=> feat: add lic4 function and associated quadrant utility function (#1)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic8Test.java
Added a function to evaluate the eighth launch interceptor condition.
- Added `lic8` function
- Added 3 unit tests for `lic8`
Closes #14
=> feat: Add LIC 8 function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/DistancefunctionTest.java
- Add calculateDistanceBetween2Points function
- Add a test for calculateDistanceBetween2Points function
- Replace distance calculation in circleContainmentCheck with calculateDistanceBetween2Points function
Closes #12
Closes #4
=> Feat: add distance function and refactor distance calculation

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/CalculateAngleTest.java, src/test/java/org/dd2480/Lic2Test.java, src/test/java/org/dd2480/ValidAngleTest.java
- added 2 functions to solve lic 2
- added Lic2Test & ValidAngleTest
closes #27
=> feat: Add checkValidAngle and lic2 functions

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic6Test.java
Added function to evaluate the sixth launch intercept condition.
* Added `lic6` function
* Added 7 unit tests for `lic6`
Closes #2
=> feat: add lic6 and unit tests for lic6 (#2)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic13Test.java
Added a function for the 13th launch intercept condition.
Also added 6 unit tests to said function.
Closes #15
=> feat: Add LIC 13 function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic2Test.java, src/test/java/org/dd2480/Lic9Test.java
- added the lic9 function
- added the Lic9Test file that includes tests for invalid input, correct input and false input
=> feat: Add lic9 and Lic9Test

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic9Test.java
- also added number of points less than 5 edge case
=> fix: Adjust tests of Lic9Test for new version

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/DistancefunctionTest.java, src/test/java/org/dd2480/Lic0Test.java
- Add lic0 function
- Add 3 tests for lic0 function
Closes #24
=> Feat lic0 function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/XDropTest.java
- added checkForXDrop func that returns true if X2 < X1
- added XDropTest file that includes one invalid input, one correct and one false input for checkForXDrop func
Closes #3
=> feat: Add checkForXDrop function for Lic #5 & 11

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic5Test.java
- added the function that corresponds to LIC5
- added a test file for lic5 that includes one throws, one correct & one false test
- closes #43
=> feat: Add lic5 function and Lic5Test file

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic11Test.java
- added the function that corresponds to LIC 11
- added tests for invalid G_PTS & one correct and one false input
- closes #46
=> feat: Add lic11 function and Lic11Test file

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic7Test.java
- Add lic7 function
- Add 4 tests for lic7 function
Closes #44
=> feat: Add lic7 function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic10Test.java
Implemented function for the 10th launch intercept condition.
* Added `lic10` function.
* Added 4 unit tests for lic10 function.
Closes: #45
=> feat: lic10 (#45)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic3Test.java
Implemented function for the 3rd launch intercept condition.
* Added `lic3` function.
* Added 3 unit tests for `lic3` function.
Closes: #42
=> feat: lic3 (#42)

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic12Test.java
- Add lic12 function
- Add 4 unit tests for lic12 function
Closes #47
=> feat: Add lic12 function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/Lic7Test.java
- Add -1 to for-loop and +1 to indexing for correct behaviour
- Add 1 unit test to account for the change
Closes #66
=> fix: lic7 function logic

report.md
Add report with members, group, essence statement, and a description of how we worked.
Closes #67
=> docs: add report.md

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/GetCmvTest.java
- Added `getCmv` to calculate the CMV (Conditions Met Vector).
- Added one test for `getCmv`
Closes #49
=> feat: Add CMV function

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/GetPumTest.java
- Added `getPum` which calculates the PUM using the CMV and LCM.
- Added two tests for `getPum`.
Closes #50
=> feat: Add function to calculate PUM

src/main/java/org/dd2480/Main.java, src/test/java/org/dd2480/GetFuvTest.java
- Added `getFuv` function.
- Added 2 tests for the `getFuv` function.
Closes #51
=> feat: Add FUV function

README.md
- Add README file with description, how to build and test, Folder structure overview and contributions.
Closes #38
=> docs: Add README file

src/main/java/org/dd2480/Main.java, src/main/java/org/dd2480/Parameters.java, src/test/java/org/dd2480/DecideTest.java
Add decide function and parameter class to store all the input parameters of the program.
Add 1 unit test for decide function, most functionality is tested in other unit tests.
Closes #58
=> feat: add decide function (#58)

src/main/java/org/dd2480/Main.java
- Added a decide function that generates a YES output.
Closes #68
=> feat: Add main which runs decide function

src/test/java/org/dd2480/DecideTest.java
* Add 2 unit tests for `decide`, one positive, one negative.
Closes #81
=> feat: add 2 decide tests

src/test/java/org/dd2480/GetPumTest.java
- Add 1 negative test for getPum function.
Closes #82
=> feat: Add getPumTest
